version: "3.8"
services:
  fastapi:
    image: fastapi-server:latest
    container_name: fastapi-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - YOUR_ENV=development
    depends_on:
      - mysql
      - redis      
    restart: unless-stopped  

  mysql:
    image: mysql:8.0.33
    container_name: fastapi-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
      MYSQL_DATABASE: fastapi
      MYSQL_ROOT_PASSWORD: fastapi
      TZ: "Asia/Seoul"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldb:/var/lib/mysql     

  redis:
    image: redis:6.2.6
    container_name: fastapi-redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: fastapi-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=bitnami      
   

volumes:
  mysqldb: